"use client";

import { useMemo, useState } from "react";
import { StyledSelect } from "@/components/ui/StyledSelect";

type Unit = "m" | "km" | "ft" | "in" | "kg" | "lb" | "c" | "f";
const groups: Record<string, Unit[]> = { Length:["m","km","ft","in"], Weight:["kg","lb"], Temperature:["c","f"] };
const labels: Record<Unit,string> = {m:"Metres",km:"Kilometres",ft:"Feet",in:"Inches",kg:"Kilograms",lb:"Pounds",c:"Celsius",f:"Fahrenheit"};
function convert(value:number,from:Unit,to:Unit){if((from==="c"||from==="f")&&(to==="c"||to==="f")){const c=from==="c"?value:(value-32)*5/9;return to==="c"?c:c*9/5+32;}const length:Record<string,number>={m:1,km:1000,ft:0.3048,in:0.0254};const weight:Record<string,number>={kg:1,lb:0.45359237};const table=from in length?length:weight;return value*table[from]/table[to];}
export function UnitConverter(){const [group,setGroup]=useState("Length");const [from,setFrom]=useState<Unit>("m");const [to,setTo]=useState<Unit>("km");const [value,setValue]=useState(1);const units=groups[group];const result=useMemo(()=>convert(value,from,to),[value,from,to]);const changeGroup=(g:string)=>{const u=groups[g];setGroup(g);setFrom(u[0]);setTo(u[1]??u[0]);};return <div className="calculator-stack"><section className="tool-panel"><div className="calculator-field"><label htmlFor="unit-group">Category</label><StyledSelect id="unit-group" value={group} onChange={changeGroup} options={Object.keys(groups).map(g=>({value:g,label:g}))}/></div><div className="calculator-field"><label htmlFor="unit-value">Value</label><input id="unit-value" type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/></div><div className="calculator-field"><label htmlFor="unit-from">From</label><StyledSelect id="unit-from" value={from} onChange={v=>setFrom(v as Unit)} options={units.map(u=>({value:u,label:labels[u]}))}/></div><div className="calculator-field"><label htmlFor="unit-to">To</label><StyledSelect id="unit-to" value={to} onChange={v=>setTo(v as Unit)} options={units.map(u=>({value:u,label:labels[u]}))}/></div></section><section className="calculator-result"><div className="result-primary"><span>Converted value</span><strong>{Number.isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:8}):"—"} {labels[to]}</strong></div></section></div>;}
