"use client";

import { useMemo, useState } from "react";

type Rgb = [number, number, number];
type Hsl = [number, number, number];

function prettyJson(value: string, minify = false) { try { return JSON.stringify(JSON.parse(value), null, minify ? 0 : 2); } catch { return "Invalid JSON."; } }
function formatText(value: string, kind: string) { if (kind === "json-minifier") return prettyJson(value, true); if (kind === "html-formatter") return value.replace(/></g, ">\n<").split("\n").map((line, i) => "  ".repeat(Math.max(0, (line.match(/^<\//) ? i - 1 : i))).concat(line.trim())).join("\n"); if (kind === "css-formatter") return value.replace(/\{/g, " {\n  ").replace(/;/g, ";\n  ").replace(/\}/g, "\n}\n").replace(/\n\s*\n/g, "\n").trim(); if (kind === "javascript-formatter") return value.replace(/\{/g, " {\n  ").replace(/;/g, ";\n").replace(/\}/g, "\n}\n").trim(); if (kind === "sql-formatter") return value.replace(/\s+(FROM|WHERE|GROUP BY|ORDER BY|HAVING|LIMIT|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN)\s+/gi, "\n$1 ").replace(/\s+/g, " ").trim(); if (kind === "xml-formatter") return value.replace(/></g, ">\n<").trim(); return value; }

function colorConvert(value: string, mode: string) {
  const hexToRgb = (hex: string): Rgb => { const h = hex.replace("#", ""); if (!/^[0-9a-f]{6}$/i.test(h)) throw new Error(); return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)]; };
  const rgbToHsl = (r: number, g: number, b: number): Hsl => { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b); let h = 0, s = 0; const l = (max + min) / 2; if (max !== min) { const d = max - min; s = l > 0.5 ? d / (2 - max - min) : d / (max + min); switch (max) { case r: h = (g - b) / d + (g < b ? 6 : 0); break; case g: h = (b - r) / d + 2; break; default: h = (r - g) / d + 4; } h /= 6; } return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)]; };
  const hslToRgb = (h: number, s: number, l: number): Rgb => { s /= 100; l /= 100; const c = (1 - Math.abs(2 * l - 1)) * s, x = c * (1 - Math.abs((h / 60) % 2 - 1)), m = l - c / 2; let r = 0, g = 0, b = 0; if (h < 60) { r = c; g = x; } else if (h < 120) { r = x; g = c; } else if (h < 180) { g = c; b = x; } else if (h < 240) { g = x; b = c; } else if (h < 300) { r = x; b = c; } else { r = c; b = x; } return [Math.round((r + m) * 255), Math.round((g + m) * 255), Math.round((b + m) * 255)]; };
  try { if (mode === "hex-rgb") return `rgb(${hexToRgb(value).join(", ")})`; if (mode === "hex-hsl") { const rgb = hexToRgb(value); const hsl = rgbToHsl(rgb[0], rgb[1], rgb[2]); return `hsl(${hsl.join(", ")}%)`; } const nums = value.match(/\d+(?:\.\d+)?/g)?.map(Number) ?? []; if (nums.length !== 3) return "Invalid color value."; const values: Rgb = [nums[0], nums[1], nums[2]]; if (mode === "rgb-hsl") { const hsl = rgbToHsl(values[0], values[1], values[2]); return `hsl(${hsl.join(", ")}%)`; } if (mode === "hsl-rgb") { const rgb = hslToRgb(values[0], values[1], values[2]); return `rgb(${rgb.join(", ")})`; } if (mode === "rgb-hex") return `#${values.map((n) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, "0")).join("").toUpperCase()}`; } catch {} return "Invalid color value.";
}

const statusCodes: Record<string, string> = { "200": "OK", "201": "Created", "204": "No Content", "301": "Moved Permanently", "302": "Found", "304": "Not Modified", "400": "Bad Request", "401": "Unauthorized", "403": "Forbidden", "404": "Not Found", "409": "Conflict", "422": "Unprocessable Content", "429": "Too Many Requests", "500": "Internal Server Error", "502": "Bad Gateway", "503": "Service Unavailable" };
const mimeTypes: Record<string, string> = { html: "text/html", css: "text/css", js: "text/javascript", json: "application/json", xml: "application/xml", yaml: "application/yaml", yml: "application/yaml", csv: "text/csv", txt: "text/plain", pdf: "application/pdf", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", svg: "image/svg+xml", webp: "image/webp", zip: "application/zip" };

function UuidGeneratorTool() {
  const [uuid, setUuid] = useState("");
  const generate = () => setUuid(crypto.randomUUID());

  return (
    <section className="tool-panel calculator-stack">
      <h2>UUID Generator</h2>
      <p className="tool-disclaimer">Generate a random UUID v4 locally in your browser.</p>
      <button type="button" className="tool-button" onClick={generate}>Generate UUID</button>
      <label className="calculator-field">
        UUID
        <input value={uuid} readOnly placeholder="Click Generate UUID" />
      </label>
    </section>
  );
}

export function DeveloperUtilityTool({ slug }: { slug: string }) {
  const [input, setInput] = useState(""); const [second, setSecond] = useState(""); const [mode, setMode] = useState("hex-rgb");
  const result = useMemo(() => { if (slug === "color-converter") return colorConvert(input, mode); if (["html-formatter", "css-formatter", "javascript-formatter", "sql-formatter", "xml-formatter", "json-minifier"].includes(slug)) return formatText(input, slug); if (slug === "xml-validator") { try { const d = new DOMParser().parseFromString(input, "application/xml"); return d.querySelector("parsererror") ? "Invalid XML" : "Valid XML"; } catch { return "Invalid XML"; } } if (slug === "url-parser") { try { const u = new URL(input); return JSON.stringify({ protocol: u.protocol, host: u.host, path: u.pathname, query: u.search, hash: u.hash, params: Object.fromEntries(u.searchParams) }, null, 2); } catch { return "Invalid URL"; } } if (slug === "http-status-lookup") return statusCodes[input.trim()] ? `${input.trim()} — ${statusCodes[input.trim()]}` : "Status code not found."; if (slug === "mime-type-lookup") { const ext = input.trim().toLowerCase().replace(/^\./, ""); return mimeTypes[ext] ?? "MIME type not found."; } if (slug === "jwt-expiry-checker") { try { const p = JSON.parse(atob(input.split(".")[1].replace(/-/g, "+").replace(/_/g, "/"))); if (!p.exp) return "No exp claim."; const left = p.exp - Math.floor(Date.now() / 1000); return left >= 0 ? `Valid — expires in ${Math.floor(left / 86400)} days.` : "Expired."; } catch { return "Invalid JWT."; } } if (slug === "text-json") return JSON.stringify(Object.fromEntries(input.split(/\r?\n/).filter(Boolean).map((l) => { const i = l.indexOf("="); return [i < 0 ? l : l.slice(0, i).trim(), i < 0 ? "" : l.slice(i + 1).trim()]; })), null, 2); if (slug === "json-path-tester") { try { const data = JSON.parse(second) as Record<string, unknown>; const path = input.trim().replace(/^\$\.?/, "").split(".").filter(Boolean); let v: unknown = data; for (const key of path) v = (v as Record<string, unknown> | undefined)?.[key]; return JSON.stringify(v, null, 2); } catch { return "Path or JSON is invalid."; } } if (slug === "regex-generator") return input ? `/${input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/` : "Enter text to escape into a regex."; if (slug === "diff-checker") { const a = input.split(/\r?\n/), b = second.split(/\r?\n/); return a.map((line, i) => line === b[i] ? `  ${line}` : `- ${line}\n+ ${b[i] ?? ""}`).join("\n"); } if (slug === "cron-generator") return `${input || "*"} ${second || "*"} * * *`; if (slug === "cron-parser") return input.trim() ? `Minute: ${input.split(/\s+/)[0] ?? "*"}\nHour: ${input.split(/\s+/)[1] ?? "*"}\nDay: ${input.split(/\s+/)[2] ?? "*"}\nMonth: ${input.split(/\s+/)[3] ?? "*"}\nWeekday: ${input.split(/\s+/)[4] ?? "*"}` : "Enter a cron expression."; return ""; }, [slug, input, second, mode]);

  if (slug === "uuid-generator") return <UuidGeneratorTool />;

  const title = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return <section className="tool-panel calculator-stack"><h2>{title}</h2>{slug === "color-converter" && <label className="calculator-field">Conversion<select value={mode} onChange={(e) => setMode(e.target.value)}><option value="hex-rgb">HEX → RGB</option><option value="rgb-hex">RGB → HEX</option><option value="hex-hsl">HEX → HSL</option><option value="rgb-hsl">RGB → HSL</option><option value="hsl-rgb">HSL → RGB</option></select></label>}{slug === "cron-generator" && <div className="date-tool-grid"><label className="calculator-field">Minute<input value={input} onChange={(e) => setInput(e.target.value)} placeholder="*/5" /></label><label className="calculator-field">Hour<input value={second} onChange={(e) => setSecond(e.target.value)} placeholder="*" /></label></div>}{slug === "diff-checker" && <div className="json-editor-grid"><label><span className="editor-label">Original</span><textarea value={input} onChange={(e) => setInput(e.target.value)} /></label><label><span className="editor-label">Modified</span><textarea value={second} onChange={(e) => setSecond(e.target.value)} /></label></div>}{slug === "json-path-tester" && <label className="calculator-field">JSON<textarea value={second} onChange={(e) => setSecond(e.target.value)} placeholder='{"user":{"name":"Toolbench"}}' /></label>}{slug !== "diff-checker" && slug !== "json-path-tester" && <label className="calculator-field">Input<textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="Enter or paste your data here..." /></label>}{slug === "json-path-tester" && <label className="calculator-field">JSONPath<input value={input} onChange={(e) => setInput(e.target.value)} placeholder="$.user.name" /></label>}<label className="calculator-field">Result<textarea value={result} readOnly /></label></section>;
}
